version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.python
    image: myimage:latest 
    networks:
      backend:
        ipv4_address: 172.20.0.5
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8
    networks:
      backend:
        ipv4_address: 172.20.0.10
    restart: on-failure
    env_file:
      - .env

networks:
  backend:
    driver: bridge

