FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY main.py ./
ENV DB_HOST=new-mysql-db \
    DB_USER= \
    DB_PASSWORD= \
    DB_NAME=example
EXPOSE 5000
CMD ["python", "main.py"]
